### ISSUE TITLE
[idea] Copy docs for completeness

### ISSUE THREAD

**Issue by Sachaa-Thanasius** [AbstractUmbra/audioop#21]
This is based on what other PEP 594 "dead battery" LTS packages are including, so I figured it doesn't hurt to consider: would you be open to having a docs folder with the CPython audioop documentation in it? It's one rst file, AFAIK.

There's no reason to doubt docs.python.org wouldn't keep the docs around in some way, but having them here could make finding a functional version of them easier and faster for future users. Just a thought.

**Comment by AbstractUmbra** [comment]
It's one thing to keep the docs here, but then I'd probably need to set up RTD for them and whatnot.

I don't see it being an issue at all, will just need 10-15m of time to get set up. I'm all for it.

**Comment by Sachaa-Thanasius** [comment]
I didn't even consider RTD; I'd just assumed GitHub's rST rendering would be good enough for most people, and takes next to no effort.

**Comment by AbstractUmbra** [comment]
Even that I'd be open to. You're welcome to pr it, or I'll get it maybe
tomorrow since I'm sadly not at my workstation until then.
